[project]
name = "polaroids"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Cole Hudson", email = "m.cole.hudson@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "polars>=1.40.0",
]

[project.scripts]
polaroids = "polaroids:main"

[build-system]
requires = ["uv_build>=0.11.7,<0.12.0"]
build-backend = "uv_build"
