"""Small package to generated clean type stubs for polars dataframe columns."""

import re
from pathlib import Path
from typing import Union

import polars as pl


@pl.api.register_dataframe_namespace('c')
class ColumnAccessor:
    """Provides dot notation access to polars dataframe columns i.e. `df.c.col_name`."""

    def __init__(self, df: pl.DataFrame) -> None:
        """Initializes column accessor.

        Args:
            df (pl.DataFrame): Polars dataframe to wrap
        """
        self._df = df

    def __getattr__(self, col_name: str) -> pl.Expr:
        """Gets named column and returns a polars expression.

        Args:
            col_name (str): name of dataframe column

        Returns:
            pl.Expr: Polars expression representing the named column
        """
        return pl.col(col_name)

    def __dir__(self) -> list[str]:
        """Returns list of column names for environments which need it.

        Returns:
            list[str]: list of column names in dataframe
        """
        return self._df.columns


@pl.api.register_lazyframe_namespace('c')
class LazyColumnAccessor:
    """Provides dot notation access to polars lazyframe columns i.e. `df.c.col_name`."""

    def __init__(self, df: pl.LazyFrame) -> None:
        """Initializes column accessor.

        Args:
            df (pl.LazyFrame): Polars lazyframe to wrap
        """
        self._df = df

    def __getattr__(self, col_name: str) -> pl.Expr:
        """Gets named column and returns a polars expression.

        Args:
            col_name (str): name of lazyframe column

        Returns:
            pl.Expr: Polars expression representing the named column
        """
        return pl.col(col_name)

    def __dir__(self) -> list[str]:
        """Returns list of column names for environments which need it.

        Returns:
            list[str]: list of column names in lazyframe
        """
        return self._df.columns


def generate_stubs(
    df: Union[pl.DataFrame, pl.LazyFrame],
    class_name: str,
    file_path: Union[Path, str] = 'polaroids.py',
    lowercase: bool = False,
) -> tuple[Union[pl.DataFrame, pl.LazyFrame], dict[str, str]]:
    """Generate stubs for polars dataframe schema for IDE autocompletion.

    Also cleans column names to valid python identifiers returns original object with
    updated column names

    Args:
        df (Union[pl.DataFrame, pl.LazyFrame]): Polars dataframe or lazyframe from which
            to generate stubs
        class_name (str): name of class in generated stub files. Should also be used in
            code as type hint for dataframes with these columns
        file_path (Union[Path, str]):path to write stub file. Defaults to "polaroids.py"
        lowercase (bool): will lowercase columns names when transforming to valid python
            identifiers. Defaults to False

    Returns:
        Union[pl.DataFrame, pl.LazyFrame]: Original dataframe/lazyframe with the columns
            renamed to valid python identifiers
    """
    schema = df.schema

    lines = [f'# --- START {class_name} ---', f'class _{class_name}_cols:']

    rename_mapping = {}
    for col_name, dtype in schema.items():
        safe_col_name = re.sub(r'[^0-9a-zA-Z_]', '_', col_name)
        safe_col_name = re.sub(r'_+', '_', safe_col_name).strip('_')

        if not safe_col_name:
            safe_col_name = '_empty_'
        if safe_col_name[0].isdigit():
            safe_col_name = f'_{safe_col_name}'
        if lowercase:
            safe_col_name = safe_col_name.lower()
        if safe_col_name != col_name:
            rename_mapping[col_name] = safe_col_name
            lines.append(
                f'{safe_col_name}: pl.Expr # dtype: {dtype}, original name:{col_name}'
            )
        else:
            lines.append(f'    {safe_col_name}: pl.Expr # dtype: {dtype}')

    lines.extend(
        [
            '',
            f'class {class_name}(pl.DataFrame):',
            f'    c: _{class_name}_cols',
            f'# --- END {class_name} ---',
        ]
    )
    new_text = '\n'.join(lines)
    path = Path(file_path)

    if path.exists():
        content = path.read_text()
    else:
        content = '\n'.join(
            ['# Stub file generated by polaroids', 'import polars as pl']
        )

    search_pattern = re.compile(
        rf'# --- START {class_name} ---.*?# --- END {class_name} ---\n*', re.DOTALL
    )

    if search_pattern.search(content):
        new_content = search_pattern.sub(new_text + '\n', content)
    else:
        new_content = content + new_text + '\n'

    if not (path.exists() and content == new_content):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(new_content, encoding='utf-8')

    if rename_mapping:
        print(f'--- Renamed Columns for {class_name} ---')
        for old, new in rename_mapping.items():
            print(f"    '{old}' -> '{new}'")
        df = df.rename(rename_mapping)

    return df, rename_mapping
